// Netlify Function (v2 API) backing the site's chat widget. Runs
// server-side so the Anthropic API key never reaches the browser.
//
// site-content.json is generated by scripts/build-chat-context.mjs as part
// of `npm run build`, from the site's own prerendered HTML. Earlier
// versions of this function stuffed the *entire* corpus (~52 pages,
// ~28.5k tokens) into every single request's system prompt - simple, but
// on any request that missed the 5-minute ephemeral prompt cache, that
// much prompt processing plus Claude's own response time risked exceeding
// this function's ~10s Netlify execution timeout, which Netlify then
// surfaces as its own gateway error page (not this function's JSON), which
// the chat widget's client-side catch-all mislabels as "couldn't reach the
// server." selectRelevantPages() below replaces that with a small
// keyword-overlap retrieval step instead, so a typical request's prompt is
// a fraction of the size regardless of how large the corpus grows.
import siteContent from './site-content.json' with { type: 'json' };
import { members } from '../../src/data/members';

const ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';
const MODEL = 'claude-sonnet-5';
const MAX_HISTORY_MESSAGES = 12;

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

interface SitePage {
  url: string;
  title: string;
  text: string;
}

const LANGUAGE_NAMES: Record<string, string> = { en: 'English', kn: 'Kannada', ta: 'Tamil' };

// Always included regardless of query match, so generic/greeting questions
// ("hi", "what is TVC?") still have some grounding even when nothing in
// particular scores well against the user's own words.
const CORE_PAGE_URLS = ['/', '/about', '/visit', '/people'];

// Caps how many non-core pages get pulled in, and a hard character budget
// across the whole selection (a couple of the longer event writeups run
// 7-10k chars each, so even a few unlucky matches plus the core set could
// still add up) - keeps every request's prompt small regardless of how
// much content the site accumulates.
const MAX_RETRIEVED_PAGES = 5;
const MAX_CORPUS_CHARS = 45_000;

// This is meant to stay identical across every request (only the trailing
// "respond in X" instruction and the retrieved WEBSITE CONTENT below vary),
// so it's cached separately - see the `system` array in the Anthropic call
// below for where cache_control actually gets attached. Small and mostly
// static, so the cache savings here are minor compared to the corpus this
// replaces, but there's no reason not to.
const STATIC_INSTRUCTIONS = `You are the assistant embedded on the Tamarind Valley Collective (TVC) website (tvc.farm), a 100-acre permaculture farm community near Kanakapura, India.

Answer ONLY using the WEBSITE CONTENT provided below. Do not use any outside knowledge, and do not guess or make up details that aren't in this content.

The WEBSITE CONTENT below is a relevant subset of the site's pages, selected for this specific question — not the entire site. If a question can't be answered from what's given, say plainly that you don't have that information on the site and suggest the visitor use the Contact page (/contact) or check the relevant section directly — do not attempt to answer from general knowledge.

Keep answers concise and conversational. When helpful, mention which page the information came from.`;

// Common English function words - without filtering these, a query like
// "What is the refund policy for camping?" scores almost entirely on "the"/
// "for"/"what"/"about", which favors whichever page happens to be longest
// over whichever page is actually relevant (verified: that exact query
// pulled in a 7k-char event writeup instead of /refund-policy or
// /visit/camping before this filter existed).
const STOPWORDS = new Set([
  'the', 'and', 'for', 'are', 'but', 'not', 'you', 'your', 'with', 'that',
  'this', 'from', 'have', 'has', 'had', 'was', 'were', 'will', 'can',
  'about', 'what', 'when', 'where', 'why', 'how', 'who', 'which', 'does',
  'did', 'doing', 'there', 'their', 'they', 'them', 'his', 'her', 'its',
  'our', 'out', 'into', 'than', 'then', 'also', 'just', 'like', 'get',
  'got', 'one', 'all', 'any', 'some', 'more', 'most', 'been', 'being',
  'here', 'tell', 'know', 'want', 'need', 'please', 'thanks', 'hello', 'hey',
]);

function tokenize(text: string): string[] {
  return (text.toLowerCase().match(/[a-z0-9]{3,}/g) ?? []).filter((w) => !STOPWORDS.has(w));
}

// Crude keyword-overlap scoring, not real search - fine at this site's
// scale (~50 pages, none very long). A query word appearing in the page's
// own title is a much stronger relevance signal than one appearing
// somewhere in a long page of prose, hence the heavier title weight.
function scorePage(page: SitePage, queryWords: string[]): number {
  const titleWords = tokenize(page.title);
  const bodyLower = page.text.toLowerCase();
  let score = 0;
  for (const word of queryWords) {
    if (titleWords.includes(word)) score += 5;
    score += bodyLower.split(word).length - 1;
  }
  return score;
}

function selectRelevantPages(query: string): SitePage[] {
  const pages: SitePage[] = siteContent.pages;
  const core = pages.filter((p) => CORE_PAGE_URLS.includes(p.url));
  const queryWords = tokenize(query);

  const ranked = pages
    .filter((p) => !CORE_PAGE_URLS.includes(p.url))
    .map((page) => ({ page, score: scorePage(page, queryWords) }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, MAX_RETRIEVED_PAGES)
    .map(({ page }) => page);

  // Core pages are never dropped for budget - only ranked matches are, and
  // lowest-ranked first, so a couple of long pages can't silently push out
  // the baseline every question relies on.
  let total = core.reduce((sum, p) => sum + p.text.length, 0);
  const selected = [...core];
  for (const page of ranked) {
    if (total + page.text.length > MAX_CORPUS_CHARS) continue;
    selected.push(page);
    total += page.text.length;
  }
  return selected;
}

function formatPages(pages: SitePage[]): string {
  return pages.map((p) => `## ${p.title} (${p.url})\n${p.text}`).join('\n\n');
}

// Member cards' family/why-TVC/social fields only ever render client-side
// from a JSON blob the popup fills in on click (see MembersView.astro) -
// they're never present as static text on the page, so
// build-chat-context.mjs's HTML scrape (which only sees rendered markup)
// never picks them up, no matter how selectRelevantPages() above is tuned.
// Matching directly against this same member data (the source the site's
// own search-jump-to-card lookup also reads, see SiteSearch.astro's
// searchMembers()) fills that gap without needing the corpus to somehow
// contain content that's never actually static HTML.
function matchMembers(query: string): typeof members {
  const q = query.toLowerCase();
  return members
    .filter((m) => {
      if (q.includes(m.name.toLowerCase())) return true;
      const firstNames = m.name.split('&').map((p) => p.trim().split(/\s+/)[0]);
      return firstNames.some((n) => n.length >= 3 && new RegExp(`\\b${n.toLowerCase()}\\b`).test(q));
    })
    .slice(0, 3);
}

function formatMembers(matched: typeof members): string {
  if (!matched.length) return '';
  const blocks = matched.map((m) => {
    const lines = [`## Member: ${m.name}`];
    if (m.bio) lines.push(`What they do: ${m.bio}`);
    if (m.family) lines.push(`Family: ${m.family}`);
    const quotes = Array.isArray(m.whyTVC) ? m.whyTVC : m.whyTVC ? [m.whyTVC] : [];
    if (quotes.length) lines.push(`Why they're part of TVC: ${quotes.join(' / ')}`);
    if (m.social?.length) lines.push(`Social: ${m.social.join(', ')}`);
    return lines.join('\n');
  });
  return `--- MATCHED MEMBER PROFILES (from the Members page's full data, including fields only shown in its popup) ---\n${blocks.join('\n\n')}`;
}

// The site itself is in the middle of being translated into Kannada/Tamil
// (see src/i18n/) - the corpus stays English-only (it's generated from the
// site's English content, see the comment at the top of this file), but
// the model is perfectly capable of answering in another language while
// grounding itself in that same English source, so there's no need to
// wait for the corpus itself to be translated.
function buildLanguageInstruction(lang: string): string {
  const languageName = LANGUAGE_NAMES[lang] ?? 'English';
  return `Respond in ${languageName}, regardless of the language the WEBSITE CONTENT above happens to be written in.`;
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' },
  });
}

export default async (req: Request): Promise<Response> => {
  if (req.method !== 'POST') {
    return jsonResponse({ error: 'Method not allowed' }, 405);
  }

  let payload: { message?: string; history?: ChatMessage[]; lang?: string };
  try {
    payload = await req.json();
  } catch {
    return jsonResponse({ error: 'Invalid request body' }, 400);
  }

  const message = (payload.message ?? '').trim();
  if (!message) {
    return jsonResponse({ error: 'message is required' }, 400);
  }
  if (message.length > 2000) {
    return jsonResponse({ error: 'Message is too long.' }, 400);
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.error('[chat] ANTHROPIC_API_KEY is not set');
    return jsonResponse({ error: 'Chat is not configured yet. Please try again later.' }, 500);
  }

  const history = Array.isArray(payload.history) ? payload.history.slice(-MAX_HISTORY_MESSAGES) : [];
  const messages = [...history, { role: 'user', content: message }];

  const relevantPages = selectRelevantPages(message);
  const memberBlock = formatMembers(matchMembers(message));
  const dynamicContent = [
    `--- WEBSITE CONTENT START ---\n${formatPages(relevantPages)}\n--- WEBSITE CONTENT END ---`,
    memberBlock,
  ]
    .filter(Boolean)
    .join('\n\n');

  try {
    const anthropicRes = await fetch(ANTHROPIC_API_URL, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 1024,
        system: [
          { type: 'text', text: STATIC_INSTRUCTIONS, cache_control: { type: 'ephemeral' } },
          { type: 'text', text: dynamicContent },
          { type: 'text', text: buildLanguageInstruction(payload.lang ?? 'en') },
        ],
        messages,
      }),
    });

    if (!anthropicRes.ok) {
      const errText = await anthropicRes.text();
      console.error('[chat] Anthropic API error', anthropicRes.status, errText);
      return jsonResponse({ error: 'The assistant is having trouble right now. Please try again shortly.' }, 502);
    }

    const data = await anthropicRes.json();
    // Not always content[0] - Claude Sonnet 5 sometimes leads with a
    // `thinking` block (even though this request never asks for extended
    // thinking) before the actual `text` block, more often on follow-up
    // (multi-turn) messages than the first one. Only checking index 0 here
    // meant a real answer sitting at content[1] got silently discarded in
    // favor of the generic "couldn't come up with an answer" fallback -
    // confirmed via a raw API call reproducing exactly this shape on a
    // follow-up question that had a perfectly good answer one slot over.
    const textBlock = data.content?.find((block: { type: string }) => block.type === 'text');
    const reply = textBlock?.text ?? '';

    return jsonResponse({ reply: reply || "Sorry, I couldn't come up with an answer to that." });
  } catch (err) {
    console.error('[chat] Unexpected error', err);
    return jsonResponse({ error: 'Something went wrong. Please try again.' }, 500);
  }
};

export const config = {
  path: '/api/chat',
};
