// Netlify Function (v2 API) backing the site's chat widget. Runs
// server-side so the Anthropic API key never reaches the browser.
//
// site-content.json is generated by scripts/build-chat-context.mjs as part
// of `npm run build`, from the site's own prerendered HTML — it is the
// *only* source of truth handed to the model. The system prompt below
// instructs Claude to answer strictly from that content and to say so when
// something isn't covered, rather than falling back on general knowledge.
import siteContent from './site-content.json' with { type: 'json' };

const ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';
const MODEL = 'claude-sonnet-5';
const MAX_HISTORY_MESSAGES = 12;

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

function buildSystemPrompt(): string {
  const corpus = siteContent.pages
    .map((p: { url: string; title: string; text: string }) => `## ${p.title} (${p.url})\n${p.text}`)
    .join('\n\n');

  return `You are the assistant embedded on the Tamarind Valley Collective (TVC) website (tvc.farm), a 100-acre permaculture farm community near Kanakapura, India.

Answer ONLY using the WEBSITE CONTENT provided below. Do not use any outside knowledge, and do not guess or make up details that aren't in this content.

If a question can't be answered from this content, say plainly that you don't have that information on the site and suggest the visitor use the Contact page (/contact) or check the relevant section directly — do not attempt to answer from general knowledge.

Keep answers concise and conversational. When helpful, mention which page the information came from.

--- WEBSITE CONTENT START ---
${corpus}
--- WEBSITE CONTENT END ---`;
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' },
  });
}

export default async (req: Request): Promise<Response> => {
  if (req.method !== 'POST') {
    return jsonResponse({ error: 'Method not allowed' }, 405);
  }

  let payload: { message?: string; history?: ChatMessage[] };
  try {
    payload = await req.json();
  } catch {
    return jsonResponse({ error: 'Invalid request body' }, 400);
  }

  const message = (payload.message ?? '').trim();
  if (!message) {
    return jsonResponse({ error: 'message is required' }, 400);
  }
  if (message.length > 2000) {
    return jsonResponse({ error: 'Message is too long.' }, 400);
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.error('[chat] ANTHROPIC_API_KEY is not set');
    return jsonResponse({ error: 'Chat is not configured yet. Please try again later.' }, 500);
  }

  const history = Array.isArray(payload.history) ? payload.history.slice(-MAX_HISTORY_MESSAGES) : [];
  const messages = [...history, { role: 'user', content: message }];

  try {
    const anthropicRes = await fetch(ANTHROPIC_API_URL, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 1024,
        system: buildSystemPrompt(),
        messages,
      }),
    });

    if (!anthropicRes.ok) {
      const errText = await anthropicRes.text();
      console.error('[chat] Anthropic API error', anthropicRes.status, errText);
      return jsonResponse({ error: 'The assistant is having trouble right now. Please try again shortly.' }, 502);
    }

    const data = await anthropicRes.json();
    const reply = data.content?.[0]?.type === 'text' ? data.content[0].text : '';

    return jsonResponse({ reply: reply || "Sorry, I couldn't come up with an answer to that." });
  } catch (err) {
    console.error('[chat] Unexpected error', err);
    return jsonResponse({ error: 'Something went wrong. Please try again.' }, 500);
  }
};

export const config = {
  path: '/api/chat',
};
