// Netlify Function (v2 API) backing the site's chat widget. Runs
// server-side so the Anthropic API key never reaches the browser.
//
// site-content.json is generated by scripts/build-chat-context.mjs as part
// of `npm run build`, from the site's own prerendered HTML. Earlier
// versions of this function stuffed the *entire* corpus (~52 pages,
// ~28.5k tokens) into every single request's system prompt - simple, but
// on any request that missed the 5-minute ephemeral prompt cache, that
// much prompt processing plus Claude's own response time risked exceeding
// this function's ~10s Netlify execution timeout, which Netlify then
// surfaces as its own gateway error page (not this function's JSON), which
// the chat widget's client-side catch-all mislabels as "couldn't reach the
// server." selectRelevantPages() below replaces that with a small
// keyword-overlap retrieval step instead, so a typical request's prompt is
// a fraction of the size regardless of how large the corpus grows.
import {
  selectRelevantPages,
  formatPages,
  matchMembers,
  formatMembers,
  buildLanguageInstruction,
  callAnthropic,
} from './lib/site-retrieval';

const MODEL = 'claude-sonnet-5';
const MAX_HISTORY_MESSAGES = 12;

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

// This is meant to stay identical across every request (only the trailing
// "respond in X" instruction and the retrieved WEBSITE CONTENT below vary),
// so it's cached separately - see the `system` array in the Anthropic call
// below for where cache_control actually gets attached. Small and mostly
// static, so the cache savings here are minor compared to the corpus this
// replaces, but there's no reason not to.
const STATIC_INSTRUCTIONS = `You are the assistant embedded on the Tamarind Valley Collective (TVC) website (tvc.farm), a 100-acre permaculture farm community near Kanakapura, India.

Answer ONLY using the WEBSITE CONTENT provided below. Do not use any outside knowledge, and do not guess or make up details that aren't in this content.

The WEBSITE CONTENT below is a relevant subset of the site's pages, selected for this specific question — not the entire site. If a question can't be answered from what's given, say plainly that you don't have that information on the site and suggest the visitor use the Contact page (/contact) or check the relevant section directly — do not attempt to answer from general knowledge.

Keep answers concise and conversational. When helpful, mention which page the information came from.`;

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' },
  });
}

export default async (req: Request): Promise<Response> => {
  if (req.method !== 'POST') {
    return jsonResponse({ error: 'Method not allowed' }, 405);
  }

  let payload: { message?: string; history?: ChatMessage[]; lang?: string };
  try {
    payload = await req.json();
  } catch {
    return jsonResponse({ error: 'Invalid request body' }, 400);
  }

  const message = (payload.message ?? '').trim();
  if (!message) {
    return jsonResponse({ error: 'message is required' }, 400);
  }
  if (message.length > 2000) {
    return jsonResponse({ error: 'Message is too long.' }, 400);
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.error('[chat] ANTHROPIC_API_KEY is not set');
    return jsonResponse({ error: 'Chat is not configured yet. Please try again later.' }, 500);
  }

  const history = Array.isArray(payload.history) ? payload.history.slice(-MAX_HISTORY_MESSAGES) : [];
  const messages: ChatMessage[] = [...history, { role: 'user', content: message }];

  const relevantPages = selectRelevantPages(message);
  const memberBlock = formatMembers(matchMembers(message));
  const dynamicContent = [
    `--- WEBSITE CONTENT START ---\n${formatPages(relevantPages)}\n--- WEBSITE CONTENT END ---`,
    memberBlock,
  ]
    .filter(Boolean)
    .join('\n\n');

  try {
    const result = await callAnthropic({
      apiKey,
      model: MODEL,
      maxTokens: 1024,
      system: [
        { type: 'text', text: STATIC_INSTRUCTIONS, cache_control: { type: 'ephemeral' } },
        { type: 'text', text: dynamicContent },
        { type: 'text', text: buildLanguageInstruction(payload.lang ?? 'en') },
      ],
      messages,
    });

    if (!result.ok) {
      console.error('[chat] Anthropic API error', result.status, result.errorType);

      // A 403 billing_error (out of credits) is a distinct, known failure
      // mode - worth a warmer message than the generic "having trouble"
      // catch-all, since there's nothing transient about it that "try
      // again shortly" would fix.
      if (result.errorType === 'billing_error') {
        return jsonResponse(
          { error: "Looks like I've hit my limit for the moment — try again in a bit, or reach out via the Contact page!" },
          502,
        );
      }

      return jsonResponse({ error: 'The assistant is having trouble right now. Please try again shortly.' }, 502);
    }

    return jsonResponse({ reply: result.text || "Sorry, I couldn't come up with an answer to that." });
  } catch (err) {
    console.error('[chat] Unexpected error', err);
    return jsonResponse({ error: 'Something went wrong. Please try again.' }, 500);
  }
};

export const config = {
  path: '/api/chat',
};
